### ISSUE TITLE
Collect Mariner/Azurelinux packages in container scan

### ISSUE THREAD

**Issue by pombredanne** [aboutcode-org/scancode.io#1156]
See https://packages.microsoft.com/cbl-mariner/2.0/prod/base/x86_64/Packages/
(And https://packages.microsoft.com/cbl-mariner/)

This is an RPM distro mostly used in containers @ Azure. We are already finding installed packages in SCIO container scans.

See also these related issues:
- https://github.com/nexB/vulnerablecode/issues/751 
- https://github.com/nexB/scancode-toolkit/issues/3060
- [ ] nexB/purldb#383

**Comment by pombredanne** [comment]
`/usr/share/licenses/<package>/....` has license files, as in `/usr/share/licenses/openssl/LICENSE`

**Comment by pombredanne** [comment]
See also https://github.com/microsoft/marinara to find how it is built

**Comment by pombredanne** [comment]
See https://mcr.microsoft.com/en-us/product/cbl-mariner/base/core/about for test images

**Comment by AyanSinhaMahapatra** [comment]
There are two kinds of mariner:

* base: https://mcr.microsoft.com/en-us/product/cbl-mariner/base/core/about
* distroless: https://mcr.microsoft.com/en-us/product/cbl-mariner/distroless/base/

It seems only the distroless one here has the properties mentioned in https://github.com/nexB/scancode.io/issues/1156#issuecomment-2042738884, otherwise the base images have a `/var/lib/rpm/rpmdb.sqlite` and we can create packages out of it once `mariner` is included in the list of accepted distros. But we do not assign resources to packages correctly here btw.

**Comment by AyanSinhaMahapatra** [comment]
This was completed by https://github.com/aboutcode-org/scancode.io/pull/1161, closing!
